- name: Install ftp package with apt
  hosts: nodes
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Install ftp package
      apt:
        name: ftp*
        state: latest