- name: Performapt update
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: apt update for all packages
      apt:
        name: '*'
        state: latest
