- name: multipath.conf dosyasina blacklist block ekle
  tags: multipath
  blockinfile:
    path: /etc/multipath.conf
    block: |
      blacklist {
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st|sda)[0-9]*"
      }
